version: "2"
services:
  neo4j:
    image: registry.inventec/proxy/neo4j:5.19.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    # volumes:
    #   - "/tmp/neo4j/data:/data"
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
      - NEO4J_initial_dbms_default__database=graph.db